### ISSUE TITLE
Update files in Readabilty/ directory

### ISSUE THREAD

**Issue by mjang-cobalt** [errata-ai/readability#2]
If I understand the setup process correctly, the `extends` parameter in each .yml file requires a certain value. 

Based on the current repo, when I run `vale some.md` file, I get the following error:

```
Invalid value provided [/Users/mike/Repos/cobalt-product-public-docs/styles/Readability/FleschKincaid.yml:1:10]:

   1* extends: metric
   2  message: "Try to keep the Flesch–Kincaid grade level (%s) below 8."
   3  link: https://en.wikipedia.org/wiki/Flesch%E2%80%93Kincaid_readability_tests

'extends' key must be one of [capitalization conditional consistency existence occurrence repetition substitution readability spelling sequence].
```

I no longer get the error when I change `metric` to `readability`

**Comment by jdkato** [comment]
What version of Vale are you using? This style requires the latest v2.13.0.

**Comment by mjang-cobalt** [comment]
Ah, you're right. I got the problem before I upgraded to 2.13.0. Thanks for listening, and I'll close this issue.
