### ISSUE TITLE
Can't install Vale 2.13.0 using Chocolatey and no VS Code automatic check

### ISSUE THREAD

**Issue by ivancheban** [errata-ai/readability#3]
When I run: `choco upgrade vale` it installs Vale v.2.10.0, not the latest Vale 2.13.0 required for readability check. Also, when I finally replaced vale.exe manually in the Chocolatey bin folder on Windows and tried to check the Markdown file in VS Code using the Vale extension, it doesn't show readability scores in the Problems tab. I had to run `vale myfilename.md` to see the PowerShell output for the readability.

**Comment by jdkato** [comment]
Chocolately has been updated with the latest versions now.
