### ISSUE TITLE
Unable to sync package

### ISSUE THREAD

**Issue by wilfriedroset** [errata-ai/readability#6]
`vale sync` is unable to retrieve readability package

```bash
❯ vale --version
vale version 2.16.0
❯ cat ~/.vale.ini
StylesPath = .vale/styles
MinAlertLevel = suggestion

Packages = readability

[*]
BasedOnStyles = Vale, readability

❯ vale sync
Downloading packages [0/1] █     0% | 0sGet "readability": unsupported protocol scheme ""
```

**Comment by jdkato** [comment]
The package name is actually "Readability" (capitalized). The docs have been updated to reflect this.

**Comment by jonocarroll** [comment]
Adding here since it is already listed as an issue - I have `Readability` in `Packages` but it does not appear with `vale sync` (`vale version 3.14.2`). Is there an issue with loading it?

It works fine when downloaded manually.
