### ISSUE TITLE
Configuration options to adjust the thresholds for readability rules

### ISSUE THREAD

**Issue by LukeWinikates** [errata-ai/readability#7]
I'm trying out `Vale` for use on internal documentation, and I think the readability targets are hard to hit when the text needs to use standard technical terminology. For example, I'd like to be able to set the target for `Readability.FleschReadingEase` to 60 rather than 70 from my `.vale.ini`

**Comment by jdkato** [comment]
You'll need to create your own rule that extends [`metric`](https://vale.sh/docs/topics/styles/#metric).

**Comment by LukeWinikates** [comment]
Thanks for pointing me at the metric extension point. I acknowledge that this is a way to accomplish what I asked for.

I'm not very happy with that solution. Creating a whole new file and copy-pasting an entire rule (even a short one) seems like a lot of work for such a small thing. I was hoping for something like:

```
Readability.FleischReadingEase.Condition = "< 70"
```

Since `condition` is part of the metric data model, I suspect that's a feature Vale could support without existing metrics needing to change. 🤔 I'd consider looking into that and opening an issue/PR on the Vale repo for that. Would that be welcome? unwelcome?

**Comment by jdkato** [comment]
I think you'll find that creating custom rules is the "Vale way" to do this, and is practically a requirement for creating a useful configuration.

If you find that this is too much work, there are probably other tools for readability calculations that will better fit your goals.

**Comment by LukeWinikates** [comment]
Well, it's a question of the level of effort vs the reward/interestingness of the goal. Maybe on day 40 of the Vale journey, people have an appetite for implement a house styleguide of custom rules. And spending time implementing custom rules that I care about is different from copy-paste forking something. And like I said, the `condition` field seems like it would offer a convenient way to tune something like this.

Anyway, thanks for sharing your thoughts. Have a good one.
